package enums

const (
	EVENTTYPEDEFAULT         = "DEFAULT"
	MONITOR_EVENTTYPEDEFAULT = "MONITOR_DEFAULT"
)

const (
	ApiGroupAccount              = "Account"
	ApiGroupAccountDesc          = "View and manage account"
	ApiGroupAccountRegister      = "Account Register"
	ApiGroupAccountRegisterDesc  = "Account register"
	ApiGroupAccountAccessKey     = "Account Access Key"
	ApiGroupAccountAccessKeyDesc = "View and manage access token"
	ApiGroupApplet               = "Applet"
	ApiGroupAppletDesc           = "View and manage applet"
	ApiGroupConfiguration        = "Configuration"
	ApiGroupConfigurationDesc    = "View global configuration"
	ApiGroupCronjob              = "Cronjob"
	ApiGroupCronjobDesc          = "View and manage system cronjob"
	ApiGroupDeploy               = "Deploy"
	ApiGroupDeployDesc           = "View and manage wasm vm instances"
	ApiGroupEvent                = "Event"
	ApiGroupEventDesc            = "Event handle entry"
	ApiGroupLogin                = "Login"
	ApiGroupLoginDesc            = "Account login"
	ApiGroupMonitor              = "Monitor"
	ApiGroupMonitorDesc          = "View and manage blockchain related monitor"
	ApiGroupOperator             = "Operator"
	ApiGroupOperatorDesc         = "View and manage account blockchain operator"
	ApiGroupProject              = "Project"
	ApiGroupProjectDesc          = "View and manage project"
	ApiGroupProjectConfig        = "Project Config"
	ApiGroupProjectConfigDesc    = "View and manage project config"
	ApiGroupProjectOperator      = "Project Operator"
	ApiGroupProjectOperatorDesc  = "View and manage project blockchain operator"
	ApiGroupPublisher            = "Publisher"
	ApiGroupPublisherDesc        = "View and manage publisher (device)"
	ApiGroupResource             = "Resource"
	ApiGroupResourceDesc         = "View and manage wasm resource"
	ApiGroupStrategy             = "Strategy"
	ApiGroupStrategyDesc         = "View and manage event routing strategy"
	ApiGroupTrafficLimit         = "Traffic Limit"
	ApiGroupTrafficLimitDesc     = "View and manage system traffic"
	ApiGroupWasmLog              = "Wasm Log"
	ApiGroupWasmLogDesc          = "View and manage wasm logs"
)
