@startuml

actor       "user/cli"          as cli
participant "w3bstream_backend" as srv
participant "event_publisher"   as pub
participant "wasm_vm"           as vm
participant "blockchain"        as bc

== AUTH ==

cli -> srv: POST /auth\nauth
srv -> cli: token

== REGISTER APPLET ==

cli -> srv: POST /applet\n{applet_name, author, publisher...}
srv -> srv: register applet, create applet namespace
srv -> cli: {applet_id}

== DEPLOY APPLET ==

cli -> srv: POST /deploy\n{applet_id, deploy_version, storage_location}\n{applet_id, deploy_version, assert, assert_md5}
srv -> srv: fetch applet asserts from `applet_location` or `assert`
srv -> srv: extract applet deploy info from `applet.yaml`
srv -> srv: validating(uniqueness, validation)
srv -> srv: store applet info and assert

srv -> srv: create wasm vm instance
srv -> srv: start event monitoring
srv -> cli: event pub topic(applet_name@deploy_version)

== EVENT MONITORING ==

pub -> srv: event
srv -> srv: event data memory mapping
srv -> vm : call handler(handler_name,memory_address)
vm  -> vm : event handle
vm  -> srv: handler result
srv -> srv: store result

@enduml