version: '3.3'
services:
  postgres:
    image: postgis/postgis
    command: postgres -c stats_temp_directory=/tmp
    container_name: postgis
    restart: always
    volumes:
      - ../build/var/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_passwd
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
