package schema

//go:generate toolkit gen enum Datatype
type Datatype uint8

const (
	DATATYPE_UNKNOWN Datatype = iota
	DATATYPE__INT
	DATATYPE__INT8
	DATATYPE__INT16
	DATATYPE__INT32
	DATATYPE__INT64
	DATATYPE__UINT
	DATATYPE__UINT8
	DATATYPE__UINT16
	DATATYPE__UINT32
	DATATYPE__UINT64
	DATATYPE__FLOAT32
	DATATYPE__FLOAT64
	DATATYPE__TEXT
	DATATYPE__BOOL
	DATATYPE__TIMESTAMP
)
